[tool.poetry]
name = "alpaca"
version = "0.1.0"
description = ""
authors = ["Joe Stubbs <joestubbs5@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
absl-py = "1.4.0"
accelerate = "0.19.0"
aiohttp = "3.8.4"
aiosignal = "1.3.1"
appdirs = "1.4.4"
async-timeout = "4.0.2"
attrs = "23.1.0"
certifi = "2023.5.7"
charset-normalizer = "3.1.0"
click = "8.1.3"
cmake = "3.26.3"
docker-pycreds = "0.4.0"
filelock = "3.12.0"
fire = "0.5.0"
frozenlist = "1.3.3"
fsspec = "2023.5.0"
gitdb = "4.0.10"
gitpython = "3.1.31"
huggingface-hub = "0.14.1"
idna = "3.4"
jinja2 = "3.1.2"
joblib = "1.2.0"
lit = "16.0.5"
markupsafe = "2.1.2"
mpmath = "1.3.0"
multidict = "6.0.4"
networkx = "3.1"
nltk = "3.8.1"
numpy = "1.24.3"
nvidia-cublas-cu11 = "11.10.3.66"
nvidia-cuda-cupti-cu11 = "11.7.101"
nvidia-cuda-nvrtc-cu11 = "11.7.99"
nvidia-cuda-runtime-cu11 = "11.7.99"
nvidia-cudnn-cu11 = "8.5.0.96"
nvidia-cufft-cu11 = "10.9.0.58"
nvidia-curand-cu11 = "10.2.10.91"
nvidia-cusolver-cu11 = "11.4.0.1"
nvidia-cusparse-cu11 = "11.7.4.91"
nvidia-nccl-cu11 = "2.14.3"
nvidia-nvtx-cu11 = "11.7.91"
openai = "0.27.6"
packaging = "23.1"
pathtools = "0.1.2"
protobuf = "4.23.1"
psutil = "5.9.5"
pyyaml = "6.0"
regex = "2023.5.5"
requests = "2.30.0"
rouge-score = "0.1.2"
sentencepiece = "0.1.99"
sentry-sdk = "1.23.1"
setproctitle = "1.3.2"
six = "1.16.0"
smmap = "5.0.0"
sympy = "1.12"
termcolor = "2.3.0"
tokenizers = "0.13.3"
torch = "2.0.1"
tqdm = "4.65.0"
transformers = "4.29.2"
triton = "2.0.0"
typing-extensions = "4.5.0"
urllib3 = "1.26.15"
wandb = "0.15.3"
yarl = "1.9.2"
deepspeed = "^0.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
